### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by RMuskovets** [pizzaoverhead/FreeIva#1]
I know this is a WIP mod that shouldn't be used, but in past I really loved playing with it.
Could you publish a .zip so that I don't have to install VS/Rider along with Unity and compile it myself?
Thanks.

**Comment by pizzaoverhead** [comment]
Working on it! There are a few things that need fixed first, but I plan to have a new release once they're done.

**Comment by pizzaoverhead** [comment]
Fixed in latest release ;)

**Comment by RMuskovets** [comment]
TYSM!
