### ISSUE TITLE
Neart Future Construction Support

### ISSUE THREAD

**Issue by JonnyOThan** [pizzaoverhead/FreeIva#104]
Need IVAs built:

- [x] octo pressurized adapter
- [x] octo pressurized angular connector
- [x] octo pressurized hub
- [x] octo pressurized truss
- [x] octo pressurized truss mini
- [x] octo pressurized truss XL
- [x] docking ports

**Comment by OsirisRaptor** [comment]
The octotrusses have manned parts:
https://github.com/post-kerbin-mining-corporation/NearFutureConstruction/tree/master/GameData/NearFutureConstruction/Parts/Truss/truss-octo
The interior from the long tubes in SSPX might fit but I haven't tested.

First Draft ToDo List:
[truss-octo-01.cfg](https://github.com/post-kerbin-mining-corporation/NearFutureConstruction/blob/master/GameData/NearFutureConstruction/Parts/Truss/truss-octo/truss-octo-01.cfg)

[truss-octo-02.cfg](https://github.com/post-kerbin-mining-corporation/NearFutureConstruction/blob/master/GameData/NearFutureConstruction/Parts/Truss/truss-octo/truss-octo-02.cfg)

[truss-octo-03.cfg](https://github.com/post-kerbin-mining-corporation/NearFutureConstruction/blob/master/GameData/NearFutureConstruction/Parts/Truss/truss-octo/truss-octo-03.cfg)

[truss-octo-04.cfg](https://github.com/post-kerbin-mining-corporation/NearFutureConstruction/blob/master/GameData/NearFutureConstruction/Parts/Truss/truss-octo/truss-octo-04.cfg)

[truss-octo-adapter-crew-01.cfg](https://github.com/post-kerbin-mining-corporation/NearFutureConstruction/blob/master/GameData/NearFutureConstruction/Parts/Truss/truss-octo/truss-octo-adapter-crew-01.cfg)
[Fix cargo in 1.10](https://github.com/post-kerbin-mining-corporation/NearFutureConstruction/commit/db10cbe4aabb5b1e7f4affb70e369c38efbd969c)
2 years ago
[truss-octo-adapter-crew-01.mu](https://github.com/post-kerbin-mining-corporation/NearFutureConstruction/blob/master/GameData/NearFutureConstruction/Parts/Truss/truss-octo/truss-octo-adapter-crew-01.mu)

[truss-octo-angled-crew-01.cfg](https://github.com/post-kerbin-mining-corporation/NearFutureConstruction/blob/master/GameData/NearFutureConstruction/Parts/Truss/truss-octo/truss-octo-angled-crew-01.cfg)
[Fix cargo in 1.10](https://github.com/post-kerbin-mining-corporation/NearFutureConstruction/commit/db10cbe4aabb5b1e7f4affb70e369c38efbd969c)
2 years ago
[truss-octo-angled-crew-01.mu](https://github.com/post-kerbin-mining-corporation/NearFutureConstruction/blob/master/GameData/NearFutureConstruction/Parts/Truss/truss-octo/truss-octo-angled-crew-01.mu)

[truss-octo-crew-01.cfg](https://github.com/post-kerbin-mining-corporation/NearFutureConstruction/blob/master/GameData/NearFutureConstruction/Parts/Truss/truss-octo/truss-octo-crew-01.cfg)

[truss-octo-crew-02.cfg](https://github.com/post-kerbin-mining-corporation/NearFutureConstruction/blob/master/GameData/NearFutureConstruction/Parts/Truss/truss-octo/truss-octo-crew-02.cfg)

[truss-octo-crew-03.cfg](https://github.com/post-kerbin-mining-corporation/NearFutureConstruction/blob/master/GameData/NearFutureConstruction/Parts/Truss/truss-octo/truss-octo-crew-03.cfg)

[truss-octo-docking-125.cfg](https://github.com/post-kerbin-mining-corporation/NearFutureConstruction/blob/master/GameData/NearFutureConstruction/Parts/Truss/truss-octo/truss-octo-docking-125.cfg)

[truss-octo-docking-25.cfg](https://github.com/post-kerbin-mining-corporation/NearFutureConstruction/blob/master/GameData/NearFutureConstruction/Parts/Truss/truss-octo/truss-octo-docking-25.cfg)

[truss-octo-docking-octo.cfg](https://github.com/post-kerbin-mining-corporation/NearFutureConstruction/blob/master/GameData/NearFutureConstruction/Parts/Truss/truss-octo/truss-octo-docking-octo.cfg)

[truss-octo-drone-01.cfg](https://github.com/post-kerbin-mining-corporation/NearFutureConstruction/blob/master/GameData/NearFutureConstruction/Parts/Truss/truss-octo/truss-octo-drone-01.cfg)

[truss-octo-hub-crew-01.cfg](https://github.com/post-kerbin-mining-corporation/NearFutureConstruction/blob/master/GameData/NearFutureConstruction/Parts/Truss/truss-octo/truss-octo-hub-crew-01.cfg)
