### ISSUE TITLE
HabTech2 support

### ISSUE THREAD

**Issue by JonnyOThan** [pizzaoverhead/FreeIva#106]
- [x] ht2beam_IVA
- [x] ht2_cupolaIVA
- [x] ht2_destinyIVA
- [x] ht2_genericMedium
- [x] ht2_genericShort
- [x] ht2_harmonyIVA
- [x] ht2_kiboIVA
- [x] ht2_questIVA
- [x] ht2_sciNodeIVA
- [x] ht2_unityIVA
- [x] beam require inflation
- [x] docking adapter
- [x] audit other parts (logistics? passthrough?)
- [x] something wrong with the unity module

**Comment by JonnyOThan** [comment]
https://forum.kerbalspaceprogram.com/index.php?/topic/133501-112x-habtech2-stockalike-iss-parts-026/&do=findComment&comment=4192810

Well, apparently the older habtech has IVAs

**Comment by OsirisRaptor** [comment]
These are the MM files for the interiors I patched from LonesomeRobots into Habtech II.
[MM-HT2-Port-HT-IVA.cfg.txt](https://github.com/pizzaoverhead/FreeIva/files/10532315/MM-HT2-Port-HT-IVA.cfg.txt)
[MM-HT2-Port-LR-IVA.cfg.txt](https://github.com/pizzaoverhead/FreeIva/files/10532316/MM-HT2-Port-LR-IVA.cfg.txt)
[MM-X20-IVA.cfg.txt](https://github.com/pizzaoverhead/FreeIva/files/10532317/MM-X20-IVA.cfg.txt)
The X-20 is from this mod:
https://forum.kerbalspaceprogram.com/index.php?/topic/184435-1120-%D0%B6-20-moroz-spaceplane/
There shouldn't be any clipping.
The format isn't ideal so if you have any questions ask, or if this is useless that is good feedback too.

**Comment by JonnyOThan** [comment]
@OsirisRaptor this looks great!  Are these patches part of some other mod?  Do you mind if I include them (more likely, use them as a starting point) in freeiva?
