### ISSUE TITLE
BDB Support

### ISSUE THREAD

**Issue by JonnyOThan** [pizzaoverhead/FreeIva#117]
Other

- [x] look through CLS patches
- [ ] Can't enter seats in LM after entering another part because it doesn't have a shell collider (needs code fix to find bounds of other colliders)
- [ ] Can we do anything about the hatch valves that are separate props?
- [ ] Depth masks?

Internals

- [x] bluedog_Apollo_CrewPod_5crew / bdbKP0110internal2
- [x] BDB_Gemini_LanderCan_Int
- [x] BealeGeminiInt / Gemini_A_Int
- [x] Lunar2 - seems to have a freeiva model already? but no supporting modules..
- [x] Lunar3 - has freeiva model
- [x] LunarLab - has freeiva model
- [x] Lunar2Shelt - has freeiva model
- [x] bdb_1p2iva
- [x] bdb_mol_iva_large_module
- [x] bdb_mol_iva_main_lab
- [x] bdb_mol_iva_mercury
- [x] bdb_mol_iva_small_module
- [x] bdb_mol_iva_small_tube
- [x] bdb_skylab_OWS_iva
- [x] bdb_TRAILS_Gemini_B_Interior

Reviva support

- [x] bluedog_Skylab_WetWorkshop
- [x] bluedog_Saturn_S2_wetWorkshop
- [x] bluedog_Skylab_VFB_lightweightWetWorkshop

Docking Ports

- [x] bluedog_Apollo_CADS_active / bluedog_Apollo_CADS_passive
- [x] bluedog_Apollo_ConeDockingPort / bluedog_Apollo_ProbeDockingPort
- [x] bluedog_Apollo_APAS75
- [x] bluedog_MOL_ForkDockingPort / bluedog_MOL_RingDockingPort
- [x] bluedog_MOL_DockingPort

Things that reuse stock IVAs and need FreeIva hookup

- [x] bluedog_Apollo_Block4_MissionModule
- [x] bluedog_Skylab_VFB_ESM
- [x] bluedog_Apollo_Block3_MissionModule
- [x] bluedog_Gemini_InflatableAirlock (this uses Making History IVA)
- [ ] bluedog_Mercury_Capsule (uses mk1pod_IVA)

Crewed parts without IVAs

- [x] bluedog_Skylab_EOSS_interstageModule
- [x] bluedog_Skylab_multipleDockingAdapter
- [x] bluedog_Skylab_airlockModule (plus _SAF suffixes)
- [x] bluedog_Spacelab_airlockModule / bluedog_spacelab_forwardAdapter
- [x] bluedog_Skylab_dockingNodeAdapter
- [x] bluedog_Skylab_EOSS_aftMDA
- [x] bluedog_Skylab_wetWorkshop_airlockMDA
- [x] bluedog_spacelab_europeanModule
- [x] bluedog_BigG_CylindricalSM_CargoModule
- [x] bluedog_BigG_ConicSM_CargoModule
- [x] bluedog_Gemini_1p5mShortSegment
- [x] bluedog_Gemini_StructuralNode
- [x] bluedog_Apollo_ASTP_DockingAdapter
- [x] bluedog_Saturn_S2_wetWorkshop
- [x] bluedog_MOL_FiveWayAdapter
- [x] bluedog_MOL_ThreeWayAdapter
- [x] bluedog_EarlyLunarShelter
- [x] bluedog_LM_SheLab

Textures & Lights

- [x] bluedog_Skylab_EOSS_interstageModule
- [x] bluedog_Skylab_multipleDockingAdapter
- [x] bluedog_Skylab_airlockModule (plus _SAF suffixes)
- [x] bluedog_Spacelab_airlockModule / bluedog_spacelab_forwardAdapter
- [x] bluedog_Skylab_dockingNodeAdapter
- [x] bluedog_Skylab_EOSS_aftMDA
- [x] bluedog_Skylab_wetWorkshop_airlockMDA
- [x] bluedog_spacelab_europeanModule
- [x] bluedog_Gemini_1p5mShortSegment
- [x] bluedog_Gemini_StructuralNode
- [ ] bluedog_Apollo_ASTP_DockingAdapter
- [ ] bluedog_Saturn_S2_wetWorkshop
- [ ] bluedog_MOL_FiveWayAdapter
- [x] bluedog_MOL_ThreeWayAdapter
- [ ] bluedog_EarlyLunarShelter
- [ ] bluedog_LM_SheLab

Passthrough

- [x] bluedog_GeminiFerry_DockingAdapter
- [x] bluedog_MiniLab_Adapter
- [x] bluedog_Skylab_PMA
- [x] heatshield passthrough

Bugs
- [ ] skylab airlock seat module not hooked up
- [ ] skylab airlock eva hatch not working

Props

- [x] bluedog_prop_hatch
- [x] bluedog_prop_lmhatch
- [x] bluedog_prop_lmdoor
- [x] Bluedog_FlightSeat_Passenger

Deprecated

- Hermes_Crew_A_Interior

**Comment by OsirisRaptor** [comment]
This from draft 1 of my checking of Tantares, KNES, and BDB

Manned BDB Components [INCOMPLETE]
https://github.com/friznit/Unofficial-BDB-Wiki/wiki

-Crew Modules:
Hermes Personal Reentry Capsule
Leo Vinci Command Pod
Kane 11-3 Command Pod
Kane 11-80MM Orbital Mission Module
Navalia-ASTP Diplomat Docking Module
Landers: (LEM has Unlisted Variants)
Dona Lander Module (Exact Name Unclear)
Sina-MLEM Ascent Stage Cockpit

-A0RVs:
Belle ORV
Augustus RRV (Rendezvous Resupply Vehicle)
Rhea ORV
MOS-DM Docking Mechanism
Bloc I Aardvark Advanced Automated Rendezvous Docking Vehicle (AARDV)

-Stations:
MOL Laboratory Segment
Gemini Station Parts (INCOMPLETE)
Kane-OCO Telescope Mount?
Hokulani-MDA Multiple Docking Adapter
Hokulani-ALM Airlock Module
Hokulani-OWS Orbital Workshop
Hokulani-WWS Wet Workshop
Hokulani-RAM Adapter Module
Hokulani-EALM Expansion Airlock Module
Hokulani-FRM Foreign Research Module???
Houkulani Light Wet Workshop
Sarnus Flyby Mission Module

-Docking Ports:
[INCOMPLETE]

-Nodes/Adapters:
[INCOMPLETE]

**Comment by OsirisRaptor** [comment]
[-IVA COMPONENTS OF KNES,BDB,TANTARES [INCOMPLETE] .txt](https://github.com/pizzaoverhead/FreeIva/files/10735527/-IVA.COMPONENTS.OF.KNES.BDB.TANTARES.INCOMPLETE.txt)
And this is draft one for you to look over (I can do more digging I'm just not sure what you want listed)

**Comment by OsirisRaptor** [comment]
No problem, I appreciate you letting me know.
