### ISSUE TITLE
Support ACK

### ISSUE THREAD

**Issue by SofieBrink** [pizzaoverhead/FreeIva#137]
FreeIVA support for Artemis Construction Kit by Benjee10.
The mod only has 2 IVA’s one of which uses seats that are already properly supported.
The IVA’s are already fully furnished, so the things that’d need to happen would be:
- Adding collision to the exterior walls
- Making the hatches functional
- Making the seats functional

**Comment by JonnyOThan** [comment]
- [ ] Figure out why EVA hatches aren't working
- [ ] add colliders to top hatches
- [ ] add tubes to top hatches
- [ ] Fix layer on flight controls
