### ISSUE TITLE
Support The LonesomeRobots Collection

### ISSUE THREAD

**Issue by OsirisRaptor** [pizzaoverhead/FreeIva#143]
The LonesomeRobots Collection
https://spacedock.info/mod/3019/The%20LonesomeRobots%20Collection
https://github.com/AtomikkuSan/The-LonesomeRobots-Collection/

Contains incredibly well made IVAs and is multi-module designs are common. No need for artificial gravity, just internal barriers and doors between modules. 

If this mod is patched to FreeIVA I'd love to hear about how you implemented it as I use this mod's interiors with HabTech2's modules and Ж-20 "Moroz" Spaceplane via Module Manager.

(hijacking comment to add tasks)

Regular parts

- [x] ALTAIR_INTERIOR
- [x] AIRLCK_INTERIOR
- [x] ATV_INTERIOR
- [x] CUP_INTERIOR
- [x] DYNA_PASS_INTERIOR
- [x] DYNA_INTERIOR
- [x] GEM_INT
- [x] HLANDER_INTERIOR
- [x] MADV_INTERIOR
- [x] MADV_HAB_INTERIOR
- [x] MADV_LAB_INTERIOR
- [x] MBCLAB_INTERIOR
- [x] MBCPHAB_INTERIOR
- [x] ROOT_INTERIOR
- [x] SIV_STATION_Int
- [x] STMD1_INTERIOR
- [x] STMD2_INTERIOR
- [x] STSC_INTERIOR
- [x] passthrough?

Docking ports

- [x] root_docking_system
- [x] DBC Berthing mechanism

Missing internal

- [x] stnairlck
- [x] PMA
- [x] DBC Structrural module

**Comment by JonnyOThan** [comment]
Looks cool!
