### ISSUE TITLE
mk1pod: Unable to reach the hatch after unbuckling in IVA 

### ISSUE THREAD

**Issue by BonsaiDen** [pizzaoverhead/FreeIva#156]
Hey there,

first of all a happy new year to you and a huge thank you for all the hard work that goes into this mod -  it makes building realistic space stations so much more fun! :) 

Now, when it comes to the m1pod I found it a bit annoying that you cannot reach the hatch when unbuckling in IVA, which makes it a bit cumbersome since you have to go EVA and find another entry to your station. 

So I dusted off the MU importer for blender and checked the collision mesh, it seems that the part that's (generated?) from the console is just not leaving enough space for a kerbal to squeeze under it.

![Screenshot at 2023-01-02 10-20-23](https://user-images.githubusercontent.com/124674/210213069-2db92399-2bc8-42f9-b516-8cd3787c58ca.png)

As a quick "workaround" I deleted the faces selected in the above screenshot on my end, which makes the pod usable from both directions (tweaking the vertices might also be an option to find a middle ground here)

Now I'm wondering if there's any chance for this tweak to be added to the mod itself?

**Comment by JonnyOThan** [comment]
As luck would have it, I've already tweaked this collider and it'll be part of the next release.  You can test it here: https://github.com/pizzaoverhead/FreeIva/releases/tag/0.2.4-prerelease0 .   Please let me know if it doesn't work for you!
