### ISSUE TITLE
Camera rotates when in FreeIVA in atmosphere

### ISSUE THREAD

**Issue by SofieBrink** [pizzaoverhead/FreeIva#177]
Like the title says, while you're flying in the atmosphere the camera slowly rotates around. it feels like the camera might be forgetting to account for the planet's rotation. 

This video is sped up 8x to show it more clearly

https://user-images.githubusercontent.com/63377159/213933686-727cb662-fb21-4b73-9c4f-a36950323880.mp4

**Comment by JonnyOThan** [comment]
The camera in atmosphere just needs an entire pass; it's currently just using the zero-g system so it's probably keeping the same universal up vector as the ship rotates around it.

Eventually I'd like to switch to using the grounded character physics mode, and applying the ship's g-forces when you're not buckled.

**Comment by JonnyOThan** [comment]
This should pretty much be moot now.

**Comment by SofieBrink** [comment]
You wish, issue is unchanged when in zero g in atmosphere

**Comment by JonnyOThan** [comment]
Huh.  Well you could say that's physically correct - the ship is rotating around you after all.  But at least it won't happen when you're under subjective acceleration like in cruising flight.
