### ISSUE TITLE
NearFutureSpacecraft Amalthea hatch not linking correctly

### ISSUE THREAD

**Issue by embermctillhawk** [pizzaoverhead/FreeIva#179]
NearFutureSpacecraft -> Mk4-1 "Amalthea" has an issue where its bottom hatch doesn't work correctly, so when attempting to open from the Amalthea, one hatch opens but there's another hatch immediately behind it and it's impassble, and when opening from the other side, it opens to a grey wall which is also not passable.

**Comment by JonnyOThan** [comment]
Thanks! Feel free to tack on any other NFS issues in here.
