### ISSUE TITLE
Issue with latest version's Passable fuel tanks feature ?

### ISSUE THREAD

**Issue by Lucaspec72** [pizzaoverhead/FreeIva#183]
after updating to the latest version, i got this error :
![Sans titre](https://user-images.githubusercontent.com/48445530/214238328-aa352a11-c42b-4f1d-9d68-9045401ee0eb.png)
log attached :
[KSP.log](https://github.com/pizzaoverhead/FreeIva/files/10487393/KSP.log)

**Comment by Lucaspec72** [comment]
update: also seems to do this on another install that has a different modlist, will try to create a clean instance of ksp and only put b9partswitch, freeiva and the mk2-mk3 expansion mods

**Comment by JonnyOThan** [comment]
Thanks for the log. It’s probably conflicting with some other mod, but I should be able to track it down.  In the meantime you can delete FreeIVA/Squad/b9ps_fueltanks.cfg to disable the passthrough system.

**Comment by Lucaspec72** [comment]
Sorry for reopening this, but it seems that this happens not only with Configurable Containers, but any mod that allow modification of tanks contents (tested interstellarfuelswitch and b9stockpatch).
Considering this, is there any way of fixing this that doesn't involve completely disabling passable fuel tanks ? (perhaps have a option to always have passable iva ?)
