### ISSUE TITLE
hatches in inline docking ports not working with restock

### ISSUE THREAD

**Issue by JonnyOThan** [pizzaoverhead/FreeIva#185]
> turns out the hatches on the MK1 inline don't work 
they are replaced by freeiva have the handle on them etc but you cannot open them
can be opened from the other side
so if you have mk1 crew cabin - > mk1 inline docking port you can open and close the hatch from the crew cabin side but not from the other side

**Comment by SofieBrink** [comment]
Tidbit of extra weirdness. The MK2 inline port does work

**Comment by JonnyOThan** [comment]
That's good info, the key factor here is probably that all 4 variants (2 stock and 2 restock) have different animation names.

**Comment by SofieBrink** [comment]
Seems likely

**Comment by JonnyOThan** [comment]
Can't repro this.  I need a picture of the ship, detailed repro steps, and the ksp.log.

**Comment by JonnyOThan** [comment]
[sofie.zip](https://github.com/pizzaoverhead/FreeIva/files/10521974/sofie.zip)
