### ISSUE TITLE
Error with Mk2 Expansion Bicouplers

### ISSUE THREAD

**Issue by Lucaspec72** [pizzaoverhead/FreeIva#186]
it seems that there is some bug with the configuration files of the bicouplers of the MK2 Expansion mod, the attached log is from a install with quite a few mods, but it's also happening with only freeIVA and the Mk2expansion mod loaded.
![image](https://user-images.githubusercontent.com/48445530/214506159-db3a0dc0-9d82-41ad-b7f1-1e757c4690c2.png)
Full log attached :
[KSP.log](https://github.com/pizzaoverhead/FreeIva/files/10497128/KSP.log)
i've read through it quickly, it might have something to do with the back nodes not being found ?
![image](https://user-images.githubusercontent.com/48445530/214507078-e11a952d-9246-4ba3-a2cc-a189dd37fb49.png)
note: had previous version, but still happens with latest

**Comment by JonnyOThan** [comment]
Thanks for the report! Not really sure what happened there (maybe copy/pasted from the tricoupler) but it should be fixed.
