### ISSUE TITLE
Support Extra hatches from Restock

### ISSUE THREAD

**Issue by SofieBrink** [pizzaoverhead/FreeIva#194]
Most of the capsules have hatches modeled on them on the underside with restock. sadly these do not work inside the iva's for these parts.
![image](https://user-images.githubusercontent.com/63377159/215170035-377e971b-4d32-44e5-8c8b-83cbc7a5a0a0.png)

**Comment by JonnyOThan** [comment]
Not sure how feasible this is, most of the IVAs do not have space for hatches in those positions.

**Comment by SofieBrink** [comment]
Any update on whether this has any plausibility? If not i’ll close this

**Comment by JonnyOThan** [comment]
I haven't had time to look yet.  There's no harm in leaving it open until I decide one way or another.

**Comment by JonnyOThan** [comment]
Yeah I don't think this is gonna work :/

It would be pretty weird if having restock changed how your ship works with regards to FreeIva too.
