### ISSUE TITLE
[BUG] Stockalike Station Parts Expansion Redux Centrifuges : Coriolis Effect Bug with PXL-F 'Pilgrim' Centrifuge

### ISSUE THREAD

**Issue by Lucaspec72** [pizzaoverhead/FreeIva#229]
Just noticed that and idk if it affect other parts, but the PXL-F 'Pilgrim' Extensible centrifuge has a bug with it's artificial gravity. When trying to navigate the centrifuge, i get stuck on the wall of the centrifuge, pretty sure the coriolis effect is not properly canceled out for this part.

**Comment by JonnyOThan** [comment]
A screenshot of where exactly you were might be helpful.  I don't think the centrifuge code models the coriolis effect properly anyway.

**Comment by Lucaspec72** [comment]
It pretty much happens on the first floor (closest to center of centrifuge) of all arms, probably even worse on lower levels if you could get to them, but as stated previously the player justs gets stuck on the wall because of the rotational force.
![image](https://user-images.githubusercontent.com/48445530/223657218-57ade55a-d4f0-4809-9f11-2458ccf2297d.png)
not sure the screenshot will help much, but here it is. when you reach the first room/floor of the centrifuge, you're just glued to the wall and can't move.

**Comment by JonnyOThan** [comment]
It sounds like maybe you're not actually "attached" to the centrifuge - you need to press the spacebar or down ladder (ctrl) key while touching a ladder or handrail in the spinning part.

**Comment by Lucaspec72** [comment]
from what i've seen it seem to be similar to what you said, the gravity is applied but not the rotational correction, so unless i select the ladder (at least with the bigger centrifuge, haven't tested with pilgrim yet), i get stuck on the wall, and i don't think that happened before, may be mistaken though.

**Comment by JonnyOThan** [comment]
Looks like rigid body interpolation was interfering here, introduced in 0.2.8.0.  Should be fixed in the next release.
