### ISSUE TITLE
Resolve tantares issues

### ISSUE THREAD

**Issue by JonnyOThan** [pizzaoverhead/FreeIva#231]
https://forum.kerbalspaceprogram.com/index.php?/topic/210548-112-freeiva/&do=findComment&comment=4254269

- [x] heatshield passthrough
- [x]  Tantares Size 0 Parachute
- [x] Aquila Size 1 Node Adapter
- [x] virgo/soyuz internal collider
- [x] specific part "Aquila 12-A "Kvante" Laboratory"
- [ ] you recreate the Mir Docking module, and dock it to the bottom of the Krystall module, then dock a SOCK shuttle to it, you cannot pass from the Shuttle's docking module, through the Mir Docking Module, and Into Krystall
- [ ] iva patch
- [x] virgo crew module

**Comment by mordechaieliaz2009-lang** [comment]
hey how did you fix the problem with the mir docking module?
