### ISSUE TITLE
Cannot open hatch after passthrough part

### ISSUE THREAD

**Issue by JonnyOThan** [pizzaoverhead/FreeIva#250]
> I have a mk1-3 capsule. then the planetside 1.25m-0.9375m adapter then one of benjee's ports

I had assumed that the passthrough on the adapter part was what was breaking it, but there is a piece of code that tries to find hatches in connected parts.

**Comment by JonnyOThan** [comment]
Turns out this part wasn't using passthrough at all, and because it was using the empty iva shell there was no collider bounds to detect overlap with the kerbal.

**Comment by SofieBrink** [comment]
Hah! Glad its (hopefully) fixed now!
