### ISSUE TITLE
Go EVA prompt should not be visible if the airlock transform wasn't found

### ISSUE THREAD

**Issue by JonnyOThan** [pizzaoverhead/FreeIva#251]

**Comment by SofieBrink** [comment]
Maybe also don’t show it if the hatch is obstructed?

**Comment by JonnyOThan** [comment]
> Maybe also don’t show it if the hatch is obstructed?

This requires a collision test every frame; I'd rather just do it once when the user attempts to open it.

**Comment by SofieBrink** [comment]
Fair

**Comment by JonnyOThan** [comment]
I forgot about the behavior where you can use eva hatches to go eva from any airlock when the name isn't specified.  A missing airlock transform is usually caused by bad configuration anyway, so I think I'm not going to fix this.
