### ISSUE TITLE
Add FreeIVA Support for KCHS (KIU Chinese Human Spaceflight Pack)

### ISSUE THREAD

**Issue by OsirisRaptor** [pizzaoverhead/FreeIva#255]
https://spacedock.info/mod/3144/KIU%20Chinese%20Human%20Spaceflight%20Pack
https://github.com/Armo00/KIU-Pack

----

Parts with internals:

- [x] ChineseSpaceStation/Tianhe/Node Cabin/Docking_Hub.cfg/PART[KCHS_Tianhe_JDC]
- [x] ShenZhou/Part/OrbitalModule.cfg/PART[KCHS_SZ_OrbitalModule]
- [x] ShenZhou/Part/Re_entryModule.cfg/PART[KCHS_SZ_Re_entryModule]
- [x] TianGong/Part/LaboratoryModule.cfg/PART[KCHS_TG_LaboratoryModule]

Parts with docking nodes:

- [x] ChineseSpaceStation/ExperimentModule/DockingPort/SYCDJK.cfg/PART[KCHS_LaboratoryCabinModule_DockingPort]
- [x] ChineseSpaceStation/Tianhe/Docking Port/Tianhe_DockingPort.cfg/PART[KCHS_Tianhe_DockingPort]
- [x] DockingPort/passive_docking_port.cfg/PART[KCHS_Passive_Docking_Port]
- [x] DockingPort/proactive_docking_port.cfg/PART[KCHS_Proactive_Docking_Port]
- [x] ShenZhou/Part/DockingPort.cfg/PART[KCHS_SZ_DockingPort]
- [x] TianGong/Part/DockingPort.cfg/PART[KCHS_TG_DockingPort]
- [x] TianZhou/Part/DockingPort.cfg/PART[KCHS_TZ_DockingPort]

props:

- [x] internal hatch
- [x] eva hatch
- [x] extinguisher
- [x] camera
- [x] laptop
- [x] eva suit
- [x] eva helmet
- [x] handrail
- [x] snack boxes from OM_IVA
- [x] Globe
- [x] box lights

follow up

- [x] cctv camera switch going to wrong location?
- [x] laptop screen variant
- [x] handrail texture
- [x] internal hatch texture
- [x] internal hatch colliders setup
- [x] eva hatch texture
- [x] textures in TianGong IVA
- [x] Camera prop orientation and origin
- [x] OM_IVA suit and extinguisher prop transforms
- [x] extinguisher texture
- [x] extinguisher physical prop setup
- [x] glass panel in OM_IVA
- [x] light box texture
- [x] globe physical prop setup
- [x] snack box texture
- [x] snack box freeiva
- [x] gootube texture
- [x] gootube freeiva
- [x] glovebox window transparency?
- [x] hatch attachnode configs
- [x] separate freeiva hatch models

**Comment by JonnyOThan** [comment]
IVAs

- [ ] CM_IVA
- [ ] OM_IVA
- [ ] RM_IVA
- [ ] LM_IVA

- [ ] passthrough
- [ ] docking ports?

**Comment by JonnyOThan** [comment]
submitted a PR to KIU here: https://github.com/Armo00/KIU-Pack/pull/24
