### ISSUE TITLE
Support SABS MAS IVA

### ISSUE THREAD

**Issue by StoneBlue** [pizzaoverhead/FreeIva#256]
One of the few supposedly MAS-only IVA mods out there. Also one of the few that has a PCR replacement IVA.
Mostly stock replacement IVAs, so should be relatively easy to add support.

https://forum.kerbalspaceprogram.com/index.php?/topic/189891-sabs_iva-mas-enabled-iva-configs-for-stock-command-modules/

Looks lie it also needs Reviva support added or fixed: some IVAs not selectable in Reviva.

Relevant log & screenshot of my install:
https://drive.google.com/file/d/1OVM3VxNIfk4t2Y-rDv6ZzC1amQUn-FyF/view?usp=share_link

https://drive.google.com/file/d/1UB6LMyS1Pdm_T8hPogs4VHiTbhjF7Fm8/view?usp=share_link

**Comment by JonnyOThan** [comment]
I’m surprised this didn’t already work; the FreeIVA configs for stock parts generally apply to specific models, not internal cfg names.  But maybe SABS re-ships some of the stock models.
