### ISSUE TITLE
Create “hatch-free” version of station hub 

### ISSUE THREAD

**Issue by JonnyOThan** [pizzaoverhead/FreeIva#312]
With animated hatches, this space can get cramped. Could make a variant with reviva where the hatches are set to hide when connected.

**Comment by douglasdtlltd** [comment]
please this would be amazing. I made a small habitat/R&D for mun orbit, and I have to open 10 hatches. two hatches for every part.

**Comment by JonnyOThan** [comment]
So..it turns out I had already done this by default. https://github.com/pizzaoverhead/FreeIva/commit/d790983e3d5dc41834d7aa85455e8021a238ae91
