### ISSUE TITLE
The cockpit of the original game is completely black.

### ISSUE THREAD

**Issue by BaoHouxun** [pizzaoverhead/FreeIva#319]
I have installed the DE-IVAExtension, and the cockpit of other mods is normal.

**Comment by JonnyOThan** [comment]
Please provide a log file.  Since this doesn’t occur to me or anyone else, this is likely an installation issue and there’s nothing I can do without more information. Please use ckan to install FreeIVA.  I will reopen this when you’ve uploaded your KSP.log
