### ISSUE TITLE
Add acceleration to roll

### ISSUE THREAD

**Issue by JonnyOThan** [pizzaoverhead/FreeIva#322]
Translation movements have a bit of acceleration/momentum to them, and pitch/yaw are controlled by the mouse.  Roll feels too "sharp" and needs a similar ramp up/down.

Might also be interesting to apply this to pitch and yaw.

**Comment by SofieBrink** [comment]
Would be fun for some simulation i guess. Just disable all deceleration outright on all axis for both translations and rotations. “Realism mode”
