### ISSUE TITLE
Report: planetside command cabin rear hatch EVA doesn't work

### ISSUE THREAD

**Issue by JonnyOThan** [pizzaoverhead/FreeIva#386]
> So i’m having a bit of weird issue right now and i recall i believe @StormCircuit having something similar. Using the planetside command pod i shared yesterday, i cannot use the back hatch for to eva from freeiva. It says its obstructed. Looking through the little window in the hatch also reveals the interior hatch is not aligned with the exterior one as i can see the exterior hatch. Just eva-ing from external camera works fine though. Is this the same issue you had? If so where was the fix released/posted? I’m on the latest release version of both freeiva and planetside

> The portrait and the external camera clicking on the hatch both work, freeiva does not

**Comment by SofieBrink** [comment]
i feel like it has something to do with this part having a subtype that effectively moves the external hatch.  Freeiva seems to not realise this and my be checking the original postion of the hatch, which is now occlude by the part itself. 
this is also supported by the correctly positioned hatch being visible through the window of the incorrect hatch.

https://youtu.be/hSRgCnJJszk

**Comment by SofieBrink** [comment]
Yeah that's why i said, probably something to do with B9PS and freeIVA not realising the hatch position has moved

**Comment by SofieBrink** [comment]
If it runs the stock check for obstruction at the original position of the hatch then it should be obstructed

**Comment by JonnyOThan** [comment]
> If it runs the stock check for obstruction at the original position of the hatch then it should be obstructed

Shouldn't be, `airlockTransform` is a reference to the actual transform where the eva kerbal will be created.  But if there's more than one it might be referencing the wrong one.
