### ISSUE TITLE
MH Airlock spamming Null Reference errors when opened in editor

### ISSUE THREAD

**Issue by StormCircuit** [pizzaoverhead/FreeIva#396]
The inflatable airlock from MH spams the console with Null Reference errors that seem to stem from FreeIVA while in the editor. This does not seem to occur in flight. It also renders a really weird IVA (see screenshot)

closed airlock
![20240228232700_1](https://github.com/pizzaoverhead/FreeIva/assets/16582422/9fa09681-931b-4640-8012-76f222e5058b)

opened airlock
![20240228232720_1](https://github.com/pizzaoverhead/FreeIva/assets/16582422/4e109c80-c00e-4206-93f9-3a8a6e73b628)

closed again, spam stops.
![20240228232732_1](https://github.com/pizzaoverhead/FreeIva/assets/16582422/a3661436-f44a-478b-aabe-9a18ca917cf6)

KSP log file:
[KSP.log](https://github.com/pizzaoverhead/FreeIva/files/14442840/KSP.log)

**Comment by StormCircuit** [comment]
it also does not update the PAW it seems (it always says 'open' airlock) though I dont know if stock works either.

**Comment by JonnyOThan** [comment]
Caused by KSPCF: https://github.com/KSPModdingLibs/KSPCommunityFixes/issues/205
