### ISSUE TITLE
Add toy items for fun in IVA

### ISSUE THREAD

**Issue by StormCircuit** [pizzaoverhead/FreeIva#402]
I think this is a perfect candidate for KSP since it's basically learning with physics.
Some ideas:

bouncy balls
paddle ball
spinning tops
some sort of catapult/launcher item to use on other FreeIVA physics objects
magnets (not even sure how this one would work)
newton's cradle

Really anything which sounds fun

**Comment by JonnyOThan** [comment]
Probably can just be added to #223
