### ISSUE TITLE
NRE spam in GetModule

### ISSUE THREAD

**Issue by JonnyOThan** [pizzaoverhead/FreeIva#403]
[KSP - 2024-03-07T172755.997.log](https://github.com/pizzaoverhead/FreeIva/files/14530855/KSP.-.2024-03-07T172755.997.log)

**Comment by Khalendros** [comment]
Simplest [Craft File](https://www.dropbox.com/scl/fi/2sog4b673x0jh3s6m3m0w/KrakatoaNRETest.craft?rlkey=vxwh5jl0vaw13fnwoohg70ugk&dl=0) possible. The NRE shows up with just the cockpit of the OPT Mk2 cockpit on launch to any runway or launchpad. You can see it's affected by a fair few mods, so 100% I can believe it's one of those.

**Comment by Khalendros** [comment]
An interesting note, I was getting more NRE spam in a stock Mk1-3 pod, and tried using reviva to switch to the DE IVA Extension IVA on a whim. There were a bunch of fairly low importance JSICallbackAnimator errors, but no NRE when I went inside. I exited IVA and switched to the standard RPM option, and immediately got the NRE when going first-person.
