### ISSUE TITLE
Add acceleration/momentum to zerog movement

### ISSUE THREAD

**Issue by JonnyOThan** [pizzaoverhead/FreeIva#54]

**Comment by pizzaoverhead** [comment]
Need to come up with a movement system, e.g. can grab walls in range (assume magnetic gloves) and push from them, or pull towards selected props like handles (will need to decorate IVAs with lots of these.

To prevent getting trapped, have a very low acceleration reactionless "struggle" movement (with appropriately amusing sound effects).
![image](https://www.mariowiki.com/images/thumb/7/71/Yoshi_does_Flutter_Jump_YTT_art.jpg/220px-Yoshi_does_Flutter_Jump_YTT_art.jpg)

**Comment by JonnyOThan** [comment]
I think grab & pull or any kind of handrail system should be a separate issue - This one is about the simple keyboard controls needing some acceleration/momentum to them to feel more grounded.

**Comment by pizzaoverhead** [comment]
Split the grab/pull off into #78.
