### ISSUE TITLE
Exploration Rover System support

### ISSUE THREAD

**Issue by JonnyOThan** [pizzaoverhead/FreeIva#59]
- [x] ERSCrewInternal
- [x] ERSInternal
- [x] ACM (needs IVA)
- [ ] CCM (needs IVA)
- [x] Passthrough

**Comment by StoneBlue** [comment]
I might be able to help with this one. I'm in progress (slow that it is), on revamping ERS.
There will also be some added IVAs, in addition to the existing two.
