### ISSUE TITLE
Mk1-3 Command Pod hatch is off-center

### ISSUE THREAD

**Issue by numberlesstim** [pizzaoverhead/FreeIva#63]
The nose-hatch of the Mk1-3 Command Pod is off-center blocking passage

**Comment by numberlesstim** [comment]
![mk1-3 pod hatch](https://user-images.githubusercontent.com/117858473/201005789-b6493592-ffda-49ec-9c42-44fab01a4ee0.jpg)

**Comment by JonnyOThan** [comment]
There’s not a lot we can do here without rebuilding the entire IVA.

**Comment by pizzaoverhead** [comment]
Could possibly use meshcutter/procedural joining to replace the current hatch surround with a diagonal cut that arrives at the centreline of the part.
