### ISSUE TITLE
Switching to IVA plays a loud hatch closing sound

### ISSUE THREAD

**Issue by pizzaoverhead** [pizzaoverhead/FreeIva#69]
When switching from the flight view to the stock IVA view, all hatches are initialised as closed, and play their "HatchClose" sound at the same time.

**Comment by JonnyOThan** [comment]
I think this might actually be hatches *opening* from the `hideDoorWhenConnected` logic. Need to include a parameter to suppress sounds.

**Comment by JonnyOThan** [comment]
this is happening again
