### ISSUE TITLE
Structural fuselage is impassible

### ISSUE THREAD

**Issue by pizzaoverhead** [pizzaoverhead/FreeIva#71]
May need special support: external part geometry is set up to not need an IVA, but colliders and config to tell FreeIVA this is passable are needed.

**Comment by JonnyOThan** [comment]
I'm not really sure what to do with this part.  I'm not convinced that it should even be traversible in IVA: the challenge with this and cargo bays is that parts attached to the inside are in a completely separate space; they will be hard to render and interact with properly.  I neatly sidestepped that with the larger cargo bays by allowing you to go EVA directly into them, but this part is too small for that.

**Comment by pizzaoverhead** [comment]
The route I had been pursuing previously was to copy all vessel colliders to the IVA layer and coordinate system. This lets you do stuff like have a hatch open onto a solid part (e.g. in-flight docking or construction) and pysically prevent exiting that way.

With this setup, you still need to have EVA trigger colliders (same as seamless EVA) and external airlock transforms for entry and exit from tubes open at one end.
