### ISSUE TITLE
NeistAir Reupdated Support

### ISSUE THREAD

**Issue by StoneBlue** [pizzaoverhead/FreeIva#79]
Might be a good choice for airplane parts... a good portion of the mod has crewed cockpits & parts.

https://forum.kerbalspaceprogram.com/index.php?/topic/208435-neistair-reupdated-updated-by-kerbmario-112x/

- [x] 18AN-24-IVA
- [x] 18CRJ-IVA
- [x] 18DC3-IVA
- [x] 25DC9-IVA
- [x] 25B76-IVA
- [x] 31A35-IVA
- [x] 31DC10-IVA
- [x] 18PC-IVA
- [x] 25PC-Internal
- [x] 31PC-Internal
- [x] 37PC-Internal
- [ ] passthrough?
- [ ] dockingports?

**Comment by JonnyOThan** [comment]
Ugh, these are all built with different floor levels; placing hatches is going to be trouble.
